version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    networks:
      - roomie-network

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    networks:
      - roomie-network

networks:
  roomie-network:
